[build]
  publish = "."
  base = "."

# SPA redirects - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard)
# Firebase configuration is handled in the JavaScript code
# No additional environment variables needed for Firebase

# Security headers for HTML pages only
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://firestore.googleapis.com https://firebase.googleapis.com; frame-ancestors 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=1800"

# Cache control for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=3600" 