[build]
  publish = "."
  base = "."

# Redirects for single-page application
[[redirects]]
  from = "/test/*"
  to = "/test/index.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/test/index.html"
  status = 200

# Security headers for HTML pages only
[[headers]]
  for = "/test"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-ancestors 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=1800"

# Cache control for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=3600" 