[build]
  publish = "."
  base = "."

# Headers for zip files in subdirectory
[[headers]]
  for = "/test/zip/*"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/test/*.zip"
  [headers.values]
    Content-Type = "application/zip"

# Fallback for any zip files at root level (backup)
[[headers]]
  for = "*.zip"
  [headers.values]
    Content-Type = "application/zip" 